sudo: false
# Must set language to python so we can install custom python pacakges in
# docker-based travis builds
language: python
compiler:
 - gcc
 - clang
addons:
  apt:
    packages:
      - valac
      - uuid-dev
      - libevent-dev
      - libarchive-dev
      - intltool
      - re2c
      - libjansson-dev
      - libonig-dev
      - libfuse-dev
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/downloads
    - $HOME/thirdpart
install:
 - ./integration-tests/install-deps.sh
script:
 - ./integration-tests/run.py
